packages:
  - docs
  - packages/**
  - playground/**

overrides:
  '@una-ui/content>@una-ui/nuxt': 'workspace:./packages/nuxt'

catalog:
  '@antfu/eslint-config': ^5.4.1
  '@antfu/ni': ^26.1.0
  '@babel/types': ^7.28.4
  '@faker-js/faker': ^9.9.0
  '@iconify-json/heroicons': ^1.2.3
  '@iconify-json/lucide': ^1.2.69
  '@iconify-json/radix-icons': ^1.2.5
  '@iconify-json/tabler': ^1.2.23
  '@iconify-json/vscode-icons': ^1.2.32
  '@iconify/json': ^2.2.395
  '@iconify/utils': ^2.3.0
  '@nuxt/devtools': ^2.6.5
  '@nuxt/kit': ^3.19.2
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^3.19.2
  '@nuxtjs/color-mode': ^3.5.2
  '@tanstack/vue-table': ^8.21.3
  '@types/chroma-js': ^3.1.1
  '@types/fs-extra': ^11.0.4
  '@types/markdown-it': ^14.1.2
  '@types/node': ^22.18.10
  '@una-ui/content': ^48.3.0
  '@unocss/core': ^66.5.3
  '@unocss/eslint-config': ^66.5.3
  '@unocss/nuxt': ^66.5.3
  '@unocss/preset-attributify': ^66.5.3
  '@unocss/preset-icons': ^66.5.3
  '@unocss/preset-mini': ^66.5.3
  '@unocss/preset-uno': ^66.5.3
  '@unocss/reset': ^66.5.3
  '@vee-validate/nuxt': ^4.15.1
  '@vee-validate/zod': ^4.15.1
  '@vercel/analytics': ^1.5.0
  '@vue/compiler-core': ^3.5.22
  '@vue/compiler-sfc': ^3.5.22
  '@vueuse/core': ^12.8.2
  '@vueuse/integrations': ^12.8.2
  '@vueuse/nuxt': ^12.8.2
  bumpp: ^10.3.1
  chroma-js: ^3.1.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  conventional-changelog-cli: ^5.0.0
  eslint: ^9.37.0
  eslint-plugin-format: ^1.0.2
  esno: ^4.8.0
  fast-glob: ^3.3.3
  fs-extra: ^11.3.2
  ignore-dependency-scripts: ^1.0.1
  lint-staged: ^15.5.2
  magicast: ^0.3.5
  nuxt: ^3.19.2
  ohash: ^1.1.6
  pathe: ^2.0.3
  pkg-types: ^1.3.1
  reka-ui: ^2.5.1
  rimraf: ^6.0.1
  sass: ^1.93.2
  simple-git: ^3.28.0
  simple-git-hooks: ^2.13.1
  tailwind-merge: ^3.3.1
  typescript: ^5.8.3
  ufo: ^1.6.1
  unbuild: ^3.6.1
  unocss: ^66.5.3
  unocss-preset-animations: ^1.3.0
  vaul-vue: ^0.4.1
  vitest: ^3.2.4
  vue-tsc: ^2.2.12
  zod: ^3.25.76
