packages:
  - docs
  - packages/**
  - playground/**
catalog:
  '@antfu/eslint-config': ^4.16.2
  '@antfu/ni': ^24.4.0
  '@faker-js/faker': ^9.9.0
  '@headlessui/vue': ^1.7.23
  '@iconify-json/heroicons': ^1.2.2
  '@iconify-json/lucide': ^1.2.56
  '@iconify-json/radix-icons': ^1.2.2
  '@iconify-json/tabler': ^1.2.19
  '@iconify/json': ^2.2.356
  '@iconify/utils': ^2.3.0
  '@nuxt/devtools': ^2.6.2
  '@nuxt/kit': ^3.17.6
  '@nuxt/module-builder': ^1.0.1
  '@nuxt/schema': ^3.17.6
  '@nuxtjs/color-mode': ^3.5.2
  '@tanstack/vue-table': ^8.21.3
  '@types/chroma-js': ^3.1.1
  '@types/fs-extra': ^11.0.4
  '@types/markdown-it': ^14.1.2
  '@types/node': ^22.16.0
  '@una-ui/content': ^48.2.0
  '@unocss/core': ^66.0.0
  '@unocss/eslint-config': ^66.0.0
  '@unocss/nuxt': ^66.0.0
  '@unocss/preset-attributify': ^66.0.0
  '@unocss/preset-icons': ^66.0.0
  '@unocss/preset-mini': ^66.0.0
  '@vee-validate/nuxt': ^4.15.1
  '@vee-validate/zod': ^4.15.1
  '@vercel/analytics': ^1.5.0
  '@vueuse/core': ^12.8.2
  '@vueuse/integrations': ^12.8.2
  '@vueuse/nuxt': ^12.8.2
  bumpp: ^10.2.0
  chroma-js: ^3.1.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  conventional-changelog-cli: ^5.0.0
  eslint: ^9.30.1
  eslint-plugin-format: ^1.0.1
  esno: ^4.8.0
  fast-glob: ^3.3.3
  fs-extra: ^11.3.0
  ignore-dependency-scripts: ^1.0.1
  lint-staged: ^15.5.2
  nuxt: ^3.17.6
  ohash: ^1.1.6
  pathe: ^2.0.3
  reka-ui: ^2.3.2
  rimraf: ^6.0.1
  sass: ^1.89.2
  simple-git: ^3.28.0
  simple-git-hooks: ^2.13.0
  tailwind-merge: ^3.3.1
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.0.0
  unocss-preset-animations: ^1.2.1
  vaul-vue: ^0.4.1
  vitest: ^3.2.4
  vue-tsc: ^2.2.12
  zod: ^3.25.75
