/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JBtn: typeof import('./src/components/JBtn.vue')['default']
  }
}
